FROM openjdk:17-alpine

VOLUME /tmp

COPY policy-engine-opa-server/target/odm-platform-up-policy-engine-opa-server-*.jar ./application.jar

ARG SPRING_PROFILES_ACTIVE=docker
ARG JAVA_OPTS
ARG OPA_HOSTNAME=localhost
ARG OPA_PORT=8181
ARG SPRING_PORT=9009
ARG SPRING_PROPS

ENV SPRING_PROFILES_ACTIVE ${SPRING_PROFILES_ACTIVE}
ENV JAVA_OPTS ${JAVA_OPTS}
ENV OPA_HOSTNAME ${OPA_HOSTNAME}
ENV OPA_PORT ${OPA_PORT}
ENV SPRING_PORT ${SPRING_PORT}
ENV SPRING_PROPS ${SPRING_PROPS}

EXPOSE $SPRING_PORT

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS  -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE $SPRING_PROPS -jar ./application.jar" ]