version: '3.3'

services:

  # OPA Server
  opa:
    image: openpolicyagent/opa:latest-rootless
    env_file: .env
    ports:
      - "${OPA_PORT}:${OPA_PORT}"
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "--log-format=json-pretty"
      - "--set=decision_logs.console=true"
    volumes:
      - opa:/var/lib/opa/data:rw

  # Spring boot app
  odm-platform-up-adapter-validator-opa:
    depends_on:
      - opa
    image: opendatamesh/odm-platform-adapter-validator-opa:0.9.0
    env_file: .env
    ports:
      - "${SPRING_PORT}:${SPRING_PORT}"

volumes:
  opa: